[2022-08-05 04:20:52,428] {processor.py:163} INFO - Started process (PID=1239) to work on /opt/airflow/dags/my_dag.py
[2022-08-05 04:20:52,482] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-05 04:20:52,569] {logging_mixin.py:109} INFO - [2022-08-05 04:20:52,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-05 04:20:53,288] {logging_mixin.py:109} INFO - [2022-08-05 04:20:53,169] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-05 04:20:54,015] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-05 04:20:55,621] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 3.431 seconds
[2022-08-05 04:21:55,769] {processor.py:163} INFO - Started process (PID=1299) to work on /opt/airflow/dags/my_dag.py
[2022-08-05 04:21:55,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-08-05 04:21:55,785] {logging_mixin.py:109} INFO - [2022-08-05 04:21:55,785] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-08-05 04:21:55,842] {logging_mixin.py:109} INFO - [2022-08-05 04:21:55,794] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 1, in <module>
    from randint import randint
ModuleNotFoundError: No module named 'randint'
[2022-08-05 04:21:56,024] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-08-05 04:21:56,111] {processor.py:171} INFO - Processing /opt/airflow/dags/my_dag.py took 0.383 seconds
